title: 'Transient ISE Non-causality Study'
author: 'Steven Carter'
copyright: '2026'
execute:
  execute_notebooks: "off"

sphinx:
  extra_extensions:
  - sphinx_jupyterbook_latex
  config:
    project: "Transient ISE Non-causality Study"
